[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.3.1"
  export = ["test_04_04_3"]
  icon = "docs/icon.png"
  keywords = ["Kind/Sample","Type/Service","Category/Service","Internal/http"]
  name = "test_04_04_3"
  org = "ballerinacentral"
  version = "3.1.1"

