[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.3.1"
  export = ["test_04_04_1"]
  icon = "docs/icon.png"
  keywords = ["Kind/Sample","Type/RestApi","Category/Service","Internal/http"]
  name = "test_04_04_1"
  org = "ballerinacentral"
  version = "3.1.0"

